version: '3'

services:

# Dev Database
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-wordpress-db-new:/var/lib/mysql1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress

# Wordpress Image
  wordpress:
    build:
      context: . # dockerfile acccess to full folder
      dockerfile: ./Dockerfile
      args:
        - MYSQL_HOST=mysql
        - MYSQL_PORT=3306
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=wordpress
        - WORDPRESS_URL=docker
        - WORDPRESS_TITLE=my-site
        - WORDPRESS_ADMIN_USER=admin
        - WORDPRESS_ADMIN_PASSWORD=admin
        - WORDPRESS_ADMIN_MAIL=admin@example.com
    image: my-wordpress # tag as
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
    working_dir: /var/www/html
    volumes:
      - ./docker-configs/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker-configs/client_max_body_size.conf:/etc/nginx/conf.d/*.conf
      # - ./wp-content/uploads:/var/www/html/wp-content/uploads # Save Media uploads
      # - ./plugins:/var/www/html/wp-content/plugins            # Plugin development
      # - ./themes:/var/www/html/wp-content/themes              # Blog Theme development
      # - ./www:/var/www/html/
    # environment:
    #   WORDPRESS_DEV: "true"
    #   WORDPRESS_DB_HOST: mysql:3306
    #   WORDPRESS_DB_USER: root
    #   WORDPRESS_DB_PASSWORD: root
    #   WORDPRESS_DB_NAME: wordpress
    #   WORDPRESS_CURRENT_HOST: www.mywordpress.local
    #   VIRTUAL_HOST: wordpress.local

# Stored Named Data Volumes ( default /var/lib/docker/volumes/ )
# List volumes via docker volume ls
volumes:
  my-wordpress-db-new : {}
